// <auto-generated />
namespace Relationship_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedstufffromwoek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedstufffromwoek));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220253571_Added stuff from woek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
