// <auto-generated />
namespace Relationship_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedtablesandcolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedtablesandcolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201708231642122_Added tables and columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
